# Top-level Makefile for Member 1: The Navigator
# Forwards build and run targets to cpp/ directory

all:
	@$(MAKE) -C cpp

run:
	@$(MAKE) -C cpp run

clean:
	@$(MAKE) -C cpp clean

.PHONY: all run clean
